### ISSUE TITLE
ToyBricks Demo

### ISSUE THREAD

**Issue by LiushuiXiaoxia** [SnowdreamFramework/ToyBricks#9]
请问有demo吗，我自己直接玩，玩不转啊

**Comment by snowdream** [comment]
@LiushuiXiaoxia  这就是demo https://github.com/SnowdreamFramework/ToyBricks/tree/master/app

**Comment by snowdream** [comment]
实践过程中，碰到问题，可以在这里提。

**Comment by LiushuiXiaoxia** [comment]
https://github.com/LiushuiXiaoxia/ToyBricksDemo

这个是我用你的插件，写的一个demo，


lib1定义了一个Interface
lib2依赖lib1，同时实现了lib1中的接口
app 相当于一个运行容器，同时依赖lib1和lib2，那么如何配置app中的gradle文件，才能运行出来。

repo目录是lib1和lib2发布到本地maven repo，然后分别加压缩了aar文件，没有看到aar中有ToyBricks.json文件。

**Comment by snowdream** [comment]
@LiushuiXiaoxia  把我加进这个项目的维护者名单，我推送下修改。
https://github.com/LiushuiXiaoxia/ToyBricksDemo

没有出现的原因，是因为你的配置不对。

**Comment by LiushuiXiaoxia** [comment]
那麻烦你fork一下吧，然后提个pr，我来学习一下。

**Comment by snowdream** [comment]
@LiushuiXiaoxia 已经提交。 

ps: .idea不应该纳入git版本控制。

**Comment by LiushuiXiaoxia** [comment]
可以了，不过有几个问题咨询一下。

·这个插件直接使用了Kotlin，是否引入过多的class？
·在`classpath 'com.android.tools.build:gradle:2.3.1'`，貌似不行？
·这个与Dagger2是否有冲突或者是相互兼容？

**Comment by snowdream** [comment]
@LiushuiXiaoxia 
1. Kotlin和Java没太大区别，过多的class，Java也可能遇到。主要看怎么用，怎么优化，去掉冗余代码。
实在不行，不还有multidex嘛
2. 收到问题，我查下。
3. 要支持kotlin的话，可能历史版本有问题。新版本据说解决了，不知道是否上线了，你可以参考下面的博客。
https://blog.jetbrains.com/kotlin/2015/05/kapt-annotation-processing-for-kotlin/
